package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sean
 */
public class AddPassengers extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;

    public AddPassengers() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblEmpidError.setVisible(false);
        lblFnameError.setVisible(false);
        lblLnameError.setVisible(false);
        lblMnameError.setVisible(false);
        lblJobError.setVisible(false);
        lblSalaryError.setVisible(false);
        

        try {//populate mgr and deptno combo boxes 
            // populate valid mgr numbers 
            dbCon = new myDBCon();
            
            // get and populate the remaining
            rs = dbCon.executeStatement("SELECT * FROM Passengers");
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblempid = new javax.swing.JLabel();
        lblfname = new javax.swing.JLabel();
        lblJob = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        txtpsgid = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        lblEmpidError = new javax.swing.JLabel();
        lblLnameError = new javax.swing.JLabel();
        lblFnameError = new javax.swing.JLabel();
        lblJobError = new javax.swing.JLabel();
        lblSalaryError = new javax.swing.JLabel();
        txtMname = new javax.swing.JTextField();
        lblMname1 = new javax.swing.JLabel();
        lblMnameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Passengers");

        lblempid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblempid.setText("Passenger");

        lblfname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblfname.setText("First Name:");

        lblJob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJob.setText("DOB:");

        lblSal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSal.setText("Address:");

        lblLname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLname.setText("Last Name:");

        txtpsgid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpsgid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpsgidActionPerformed(evt);
            }
        });

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        txtdob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });

        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblEmpidError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblEmpidError.setForeground(new java.awt.Color(255, 0, 0));
        lblEmpidError.setText("error label");

        lblLnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblLnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblLnameError.setText("error label");

        lblFnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblFnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblFnameError.setText("error label");

        lblJobError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblJobError.setForeground(new java.awt.Color(255, 0, 0));
        lblJobError.setText("error label");

        lblSalaryError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblSalaryError.setForeground(new java.awt.Color(255, 0, 0));
        lblSalaryError.setText("error label");

        txtMname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMnameActionPerformed(evt);
            }
        });

        lblMname1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMname1.setText("Middle Name:");

        lblMnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblMnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblMnameError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblJob)
                                    .addComponent(lblSal)
                                    .addComponent(lblLname))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdob)
                                    .addComponent(txtLname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtaddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblLnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblJobError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSalaryError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblfname)
                                            .addComponent(lblempid))
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMname1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtpsgid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEmpidError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddNewEmp)
                                            .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblempid)
                    .addComponent(txtpsgid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpidError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFnameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMname1)
                    .addComponent(lblMnameError))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLnameError)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJob)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJobError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSal)
                    .addComponent(lblSalaryError))
                .addGap(62, 62, 62)
                .addComponent(btnAddNewEmp)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblEmpidError.setText("");
        lblEmpidError.setVisible(false);
        lblFnameError.setText("");
        lblFnameError.setVisible(false);
        lblMnameError.setText("");
        lblMnameError.setVisible(false);
        lblLnameError.setText("");
        lblLnameError.setVisible(false);
        lblJobError.setText("");
        lblJobError.setVisible(false);
        lblSalaryError.setText("");
        lblSalaryError.setVisible(false);
       
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtpsgid.getText().trim().isEmpty() || !isInteger(txtpsgid.getText().trim())) {
            if (txtpsgid.getText().trim().isEmpty()) {
                lblEmpidError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtpsgid.getText().trim())) {
                lblEmpidError.setText("Invalid. Must be integer.");
            }
            lblEmpidError.setVisible(true);
            result = false;
        }

        if (txtFname.getText().trim().isEmpty() || (txtFname.getText().trim().length() > 10)) {
            if (txtFname.getText().trim().isEmpty()) {
                lblFnameError.setText("Invalid. Cannot be empty.");
            } else if ((txtFname.getText().trim().length() > 10)) {
                lblFnameError.setText("Invalid. Must be < 10 chars.");
            }
            lblFnameError.setVisible(true);
            result = false;
        }
        
        if (txtLname.getText().trim().isEmpty() || (txtLname.getText().trim().length() > 10)) {
            if (txtLname.getText().trim().isEmpty()) {
                lblLnameError.setText("Invalid. Cannot be empty.");
            } else if ((txtLname.getText().trim().length() > 10)) {
                lblLnameError.setText("Invalid. Must be < 10 chars.");
            }
            lblLnameError.setVisible(true);
            result = false;
        }

        if (txtdob.getText().trim().isEmpty() || (txtdob.getText().trim().length() > 10)) {
            if (txtdob.getText().trim().isEmpty()) {
                lblLnameError.setText("Invalid. Cannot be empty.");
            } else if (txtdob.getText().trim().length() > 10) {
                lblLnameError.setText("Invalid. Must be < 10 chars.");
            }
            lblLnameError.setVisible(true);
            result = false;
        }


        if (txtaddress.getText().trim().isEmpty() || !(isInteger(txtaddress.getText().trim()) || isDouble(txtaddress.getText().trim()))) {
            if (txtaddress.getText().trim().isEmpty()) {
                lblSalaryError.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(txtaddress.getText().trim()) || isDouble(txtaddress.getText().trim()))) {
                lblSalaryError.setText("Invalid. Must be number.");
            }
            lblSalaryError.setVisible(true);
            result = false;
        }

       

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtpsgid.setText("");
        txtFname.setText("");
        txtdob.setText("");
        txtaddress.setText("");
        txtLname.setText("");
        txtMname.setText("");
        
    }

    private boolean isDuplicate(int empno) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT empno FROM emp WHERE empno = " + empno;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    

    
    
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {                    
            if (isValidData()) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO Passengers (passenger#, firstname, middlename lastname, dob, address) VALUES ("
                        + txtpsgid.getText().trim() + ", "
                        + "'" + txtFname.getText().toUpperCase() + "', "
                        + "'" + txtMname.getText().toUpperCase() + "', "
                        + "'" + txtLname.getText().toUpperCase() + "', "                        
                        + "'" + txtdob.getText().toUpperCase() + "', "
                        + txtaddress.getText() + ")"                                                                     
                        ;

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New employee added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!isDuplicate(Integer.parseInt(txtpsgid.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("Empno Already exists. Use a different employee number.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(null, "Error adding new employee.");
             javax.swing.JLabel label = new javax.swing.JLabel("Error adding new employee: " + e.getMessage());
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void txtpsgidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpsgidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpsgidActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmpidError;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblJob;
    private javax.swing.JLabel lblJobError;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblLnameError;
    private javax.swing.JLabel lblMname1;
    private javax.swing.JLabel lblMnameError;
    private javax.swing.JLabel lblSal;
    private javax.swing.JLabel lblSalaryError;
    private javax.swing.JLabel lblempid;
    private javax.swing.JLabel lblfname;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtpsgid;
    // End of variables declaration//GEN-END:variables

}


